### ISSUE TITLE
Flutter searchbox uses an old version of provider. Update to the latest version

### ISSUE THREAD

**Issue by rajatanantharam** [appbaseio/flutter-searchbox#13]
At funda we use other flutter modules which use the latest version of bloc_provider that uses provider 6.0.0. To be able to package all the modules, it is necessary that all libraries use the latest and greatest stable version of provider.

**Comment by rajatanantharam** [comment]
Created PR: https://github.com/appbaseio/flutter-searchbox/pull/14

**Comment by rajatanantharam** [comment]
Hello. Can we please have an update on when the fix will be published? This is now potentially blocking the release of the mobile apps with other flutter modules. Thanks.

**Comment by bietkul** [comment]
@rajatanantharam New versions are out.
