### ISSUE TITLE
Upgrade to Flutter 2.0

### ISSUE THREAD

**Issue by FDavidse20** [appbaseio/flutter-searchbox#7]
Hello, @bietkul, @anik-ghosh-au7, I'm working with the appbase searchbase and flutter_searchbox packages at Funda, and it would be really helpful if those packages can be upgraded to Flutter 2.0, so we can use all the latest features, like null safety. 
When do you think you'll be able to work on that? 
Thanks, 
Filip

**Comment by bietkul** [comment]
@FDavidse20 Thanks for raising this issue. We already have an open [PR](https://github.com/appbaseio/flutter-searchbox/pull/1) for `searchbase` and we want to support it for `flutter-searchbox` too. We aim to fix it by end of this week.
